---
  ###########################################################
  #         Playbook to configure Sandbox switches           #
  ###########################################################
  - name: Configuring Sandbox switches
    hosts: sandbox-switches
    connection: local

    tasks:
      - name: "Create device configurations from templates."
        template:
          src: "{{template}}"
          dest: "./{{inventory_hostname}}.conf"

      - debug: msg="./{{config}}"
      - name: "Configuring NXOS stuff."
        nxos_config:
          host: "{{inventory_hostname}}"
          src: "./{{config}}"
          transport: nxapi
