---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed on Debian.
  apt: "name={{ item }} state={{ apache_packages_state }}"
  with_items: "{{ apache_packages }}"
